FROM node:16.16.0
WORKDIR /app
COPY package*.json ./
RUN npm install
RUN mkdir -p node_modules/.cache && chmod -R 777 node_modules/.cache
COPY . .
ENV REACT_APP_STAGE=staging
EXPOSE 3000
CMD npm start -- --host 0.0.0.0