version: "3.4"
services:
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
      - /app/node_modules/
    command: npm start
  redis:
    image: redis:6.2-alpine
    ports:
      - 7000:7000
    command: ["redis-server", "--bind", "redis", "--port", "7000"]
volumes:
  data:
    driver: local
