version: "3.4"
services:
  server:
    build:
      context: ./server
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: server
    ports:
      - 5000:5000
    env_file: common.env
    volumes:
      - ./server:/app
      - /app/node_modules
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
      - /app/node_modules/
    command: npm start
  redis:
    image: redis:6.2-alpine
    restart: always
    command: ["redis-server", "--bind", "redis", "--port", "7000"]
volumes:
  data:
    driver: local
